### ISSUE TITLE
Feedback from using the Angular Wrapper

### ISSUE THREAD

**Issue by janwidmer** [donaldxdonald/embla-carousel-angular#2]
Hi There..

I have been using embla-carousel in my angular applications already for a long time. Today I wanted to update from version 7.x to the most recent one and found your wrapper. Thanks a lot for creating it.

While doing the update today, I had some Problems and started trying around and eventually tried your wrapper as a test.
By using your wrapper, I noticed some differences compared to using just the plain embla carousel:

1. Type Mismatch for options Property `align`:
<img width="977" alt="image" src="https://github.com/donaldxdonald/embla-carousel-angular/assets/3381820/5f4dfe17-fe3a-4659-8595-40434470f9c4">
2. Type Mismatch for options Property `containScroll`
<img width="802" alt="image" src="https://github.com/donaldxdonald/embla-carousel-angular/assets/3381820/ae5cea5f-9d5e-41cb-92d9-5d66cf751808">
3. The Select Event (https://www.embla-carousel.com/api/events/#select) does not seem to be emitted when using your wrapper. It should Emit when e.g. Tabbing through the slides. You can see the different behaviour here:

Working example of the Select Event being emitted using the plain embla here: https://codesandbox.io/p/sandbox/embla-carousel-slides-per-view-vanilla-forked-2x4vhj

Non Working example of the Select event using your Angular Wrapper: https://codesandbox.io/p/devbox/embla-carousel-with-angular-wrapper-zrncd8

**Comment by donaldxdonald** [comment]
Thanks to reaching out.  @janwidmer 
1. The "Type Mismatch"  problem can be solved by declaring a `EmblaOptionsType` type for the `options` object, as you wrote in the other example.

![image](https://github.com/donaldxdonald/embla-carousel-angular/assets/29999387/f502b314-c424-4db2-a1fe-ba6a56d67a4a)

![image](https://github.com/donaldxdonald/embla-carousel-angular/assets/29999387/379314e7-d046-4d22-affd-7c6f054f2bdf)

2. The Select Event
This seems to be throttle related, I'll fix it as soon as possible.

**Comment by janwidmer** [comment]
@donaldxdonald thanks for the quick fix.
