### ISSUE TITLE
Bump embla-carousel to v8.1.7 or higher

### ISSUE THREAD

**Issue by davidjerleke** [donaldxdonald/embla-carousel-angular#5]
Hi,

Just wanted to let you know that I would recommend you to bump `embla-carousel` to `v8.1.7` or higher. Read more here if you want to know why: [v.8.1.6 release](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.6).

Thanks in advance!

**Comment by donaldxdonald** [comment]
Done! @davidjerleke

**Comment by davidjerleke** [comment]
@donaldxdonald thanks for the swift response!
